# Generated by Django 4.2.19 on 2025-02-28 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('tittle_news', models.CharField(max_length=200)),
                ('subtittle_news', models.CharField(max_length=400)),
                ('text_news', models.TextField(blank=True)),
                ('image_news', models.ImageField(blank=True, upload_to='images_news/')),
                ('date_news', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
    ]
