# Generated by Django 4.2.19 on 2025-03-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Information',
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'information', 'verbose_name_plural': 'informations'},
        ),
    ]
