# Generated by Django 4.2.19 on 2025-03-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_information_alter_information_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='text_news',
            field=models.TextField(),
        ),
    ]
