# Generated by Django 4.2.19 on 2025-03-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_information_text_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
