# Generated by Django 4.2.19 on 2025-03-26 22:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_information_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image_news',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
